spring:
  application:
    name: munichway
  datasource:
    url: jdbc:postgresql://localhost:5432/munichway
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0

security:
  jwt:
    secret: "c8129e7d10e41172353610925c883a88d39567cb6636d7b36d709dbece32c327"

billing:
  unlock-fee: 1.0
  minute-rate: 0.1
  min-balance-to-rent: 5.0
  max-debt-limit: -5.0